import type { Metadata } from 'next';
import { ArrowUpRight, Compass, HeartHandshake, Sparkles, Users } from 'lucide-react';

export const metadata: Metadata = { title: 'About Us | Ascend Jvian', description: 'Learn about Ascend Jvian and the connected everyday app we are developing.' };

const values = [
  { title:'Our vision', copy:'To make essential everyday services easier to discover and access through one connected digital ecosystem.', Icon:Compass },
  { title:'Our mission', copy:'To bring financial, mobility, connectivity, shopping and entertainment services together in a simple and useful app experience.', Icon:Sparkles },
  { title:'Our focus', copy:'We design around real daily needs, clear choices and services that help people move confidently through their day.', Icon:Users },
  { title:'How we work', copy:'With care, curiosity and practical collaboration as we build the Ascend Jvian ecosystem.', Icon:HeartHandshake },
];

export default function About(){return <><a className="skip" href="#about-main">Skip to content</a><header className="wrap header privacy-header"><a href="./" className="brand" aria-label="Ascend Jvian home"><span className="mark">aj<span>↗</span></span><span>ascend<b>jvian</b></span></a><nav aria-label="Main navigation"><a href="./">Home</a><a href="./about.html" aria-current="page">About Us</a><a className="nav-cta" href="./contact.html">Contact Us <ArrowUpRight size={18}/></a></nav></header><main id="about-main"><section className="subpage-hero about-hero"><div className="wrap"><span className="eyebrow">OUR STORY</span><h1>Building one connection<br/>for everyday life.</h1></div></section><section className="wrap story-copy"><span className="eyebrow">HELLO, WE’RE ASCEND JVIAN</span><div><h2>Making room for<br/>what’s next.</h2><p>Ascend Jvian is developing a connected app for the services people use throughout their day. Our planned ecosystem spans payments, financial access, mobility, telecommunications, shopping, logistics and entertainment.</p><p>We believe useful technology should make everyday choices easier. That is why we are bringing these services closer together in a single destination designed around convenience, access and discovery.</p><p className="availability">The app is in development. Service availability and launch details will be announced as they are confirmed.</p></div></section><section className="drivers"><div className="wrap"><div className="drivers-heading"><span className="eyebrow">WHAT GUIDES US</span><h2>What drives us</h2></div><div className="driver-grid">{values.map(({title,copy,Icon})=><article key={title}><div className="driver-icon"><Icon size={30}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section></main><SiteFooter/></>}

function SiteFooter(){return <footer><div className="wrap footer-top"><a href="./" className="brand"><span className="mark">aj<span>↗</span></span><span>ascend<b>jvian</b></span></a><div className="company-details"><strong>ASCEND JVIAN SDN. BHD.</strong><span>202601020555 (1682652-X)</span></div><div className="footer-links"><a href="./about.html">About Us</a><a href="./contact.html">Contact Us</a><a href="./privacy.html">Privacy Policy</a></div></div><div className="wrap footer-bottom"><span>Copyright ©{new Date().getFullYear()} ASCEND JVIAN SDN. BHD. — Company No. 202601020555 (1682652-X)</span><span>All rights reserved.</span></div></footer>}
