import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | Ascend Jvian',
  description: 'Privacy policy for the Ascend Jvian website and planned app services.',
};

const sections = [
  { title: '1. Scope of this policy', content: <><p>This Privacy Policy explains how Ascend Jvian (“Ascend Jvian”, “we”, “us” or “our”) intends to collect, use, disclose, retain and protect personal data when you visit our website or use our future mobile application and services.</p><p>Our app is still in development. Some services described on this website may not yet be available. Before any app service launches, we will update this policy with the relevant legal entity, contact details, processing purposes, partners and choices.</p></> },
  { title: '2. Personal data we may collect', content: <><p>Depending on the service you use, we may collect:</p><ul><li>identity and profile information, such as your name, date of birth, identification details and profile preferences;</li><li>contact information, such as your mobile number, email address and mailing address;</li><li>account and security information, including login details, verification records and device authentication information;</li><li>transaction and financial information, such as wallet activity, payment records, billing details, financing information and fraud-prevention signals;</li><li>employment and income information when required for Earned Wage Access, financing or related eligibility checks;</li><li>vehicle, mobility and location information when you request parking, roadside assistance, ride-hailing, delivery or other location-based services;</li><li>purchase, ticketing, content and rewards activity across The9sen Mall, Wetix, short drama series, rewarded advertisements and Cost Per Sale services;</li><li>communications and support records; and</li><li>technical information, such as IP address, device identifiers, browser type, app version, diagnostic logs and cookie or similar technology data.</li></ul></> },
  { title: '3. How we obtain personal data', content: <><p>We may obtain personal data directly from you, automatically from your device when you use our services, from participating merchants and service providers, or from permitted third parties such as employers, payment providers, identity-verification providers, credit-reporting agencies and public sources.</p><p>This marketing website currently has no account, payment or contact form. Its hosting provider may process basic technical logs needed to deliver and secure the site.</p></> },
  { title: '4. Why we process personal data', content: <><p>We may process personal data to provide and improve requested services; create and secure accounts; verify identity; process payments and transactions; assess applications where permitted; prevent fraud and misuse; provide customer support; personalize features; operate rewards and promotions; meet legal and regulatory duties; protect users and our systems; and send marketing communications where you have a choice or consent is required.</p><p>Where information is mandatory, we will explain this at the point of collection and describe the likely consequences if it is not provided.</p></> },
  { title: '5. When we disclose personal data', content: <><p>We may disclose personal data only as needed for the stated purposes to companies within our group; payment networks and financial institutions; merchants; telco, mobility, automotive, logistics, entertainment and technology partners; identity, fraud-prevention and credit service providers; professional advisers; regulators, courts and law-enforcement bodies; and a buyer or successor in a corporate transaction.</p><p>We will require service providers acting for us to protect personal data and use it only for authorized purposes.</p></> },
  { title: '6. Cross-border transfers', content: <p>Some service providers may process personal data outside Malaysia. Where this occurs, we will use safeguards required by applicable law and take reasonable steps to ensure that the information receives an appropriate level of protection.</p> },
  { title: '7. Security and retention', content: <><p>We intend to use reasonable administrative, technical and physical safeguards appropriate to the sensitivity of the data. No method of transmission or storage is completely secure.</p><p>We will retain personal data only for as long as needed for the purposes described, to meet legal, accounting and regulatory requirements, and to resolve disputes. We will securely delete or anonymize data when it is no longer required.</p></> },
  { title: '8. Your choices and rights', content: <><p>Subject to applicable law, you may ask whether we process your personal data, request access or correction, withdraw consent, limit processing that may cause damage or distress, and object to direct marketing. You may unsubscribe from marketing through the method provided in the message.</p><p>Some requests may be limited by legal exceptions or by information we must retain. We may need to verify your identity before acting on a request.</p></> },
  { title: '9. Children’s privacy', content: <p>Our services are not intended for children unless a specific service expressly permits their use with appropriate parent or guardian involvement. We will provide additional notices and safeguards where a service is offered to children.</p> },
  { title: '10. Changes to this policy', content: <p>We may update this policy as our services and legal obligations change. We will post the revised version and update the effective date, and provide additional notice where required.</p> },
];

export default function PrivacyPolicy() {
  return <><a className="skip" href="#privacy-main">Skip to policy</a><header className="wrap header privacy-header"><a href="./" className="brand" aria-label="Ascend Jvian home"><span className="mark">aj<span>↗</span></span><span>ascend<b>jvian</b></span></a><nav aria-label="Main navigation"><a href="./">Home</a><a href="./about.html">About Us</a><a className="nav-cta" href="./contact.html">Contact Us</a></nav></header><main id="privacy-main" className="wrap policy-shell"><div className="policy-intro"><span className="eyebrow">PRIVACY AT ASCEND JVIAN</span><h1>Privacy Policy</h1></div><div className="policy-content">{sections.map(section => <section key={section.title}><h2>{section.title}</h2>{section.content}</section>)}</div></main><footer><div className="wrap footer-top"><a href="./" className="brand"><span className="mark">aj<span>↗</span></span><span>ascend<b>jvian</b></span></a><div className="company-details"><strong>ASCEND JVIAN SDN. BHD.</strong><span>202601020555 (1682652-X)</span></div><div className="footer-links"><a href="./about.html">About Us</a><a href="./contact.html">Contact Us</a><a href="./privacy.html">Privacy Policy</a><a href="#privacy-main">Back to top ↑</a></div></div><div className="wrap footer-bottom"><span>Copyright ©{new Date().getFullYear()} ASCEND JVIAN SDN. BHD. — Company No. 202601020555 (1682652-X)</span><span>All rights reserved.</span></div></footer></>;
}
